# Configurações gerais
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
delay_between_requests: 0.5  # em segundos
max_depth: 3  # nível máximo de crawling
payloads_file: "./payloads.txt"

# Análise de resposta
use_headless_browser: false  # ativa Selenium para detectar execução real

# Relatório
save_report: true
report_format: "json"  # ou "csv"
